# deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ltpm-deployment
  labels:
    app: ltpm
spec:
  replicas: 1 # LTPM 컨트롤러는 하나만 실행
  selector:
    matchLabels:
      app: ltpm
  template:
    metadata:
      labels:
        app: ltpm
    spec:
      # Pod가 사용할 ServiceAccount(신분증)를 2단계에서 만든 것으로 지정 (매우 중요!)
      serviceAccountName: ltpm-sa
      containers:
        - name: ltpm-controller
          image: kyohyunchoo/ltpm:1.0
          imagePullPolicy: Always
